name: ZJU-nCov-Hitcarder Sample

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        users: [user1, user2]
        include:
          - org: user1
            username: ZJU_USERNAME
            password: ZJU_PASSWORD
            dingtalk_token: DINGTALK_TOKEN
            pushplus_token: ''
            serverchan_key: ''
          - org: user2
            username: ZJU_USERNAME
            password: ZJU_PASSWORD
            dingtalk_token: ''
            pushplus_token: PUSHPLUS_TOKEN
            serverchan_key: ''
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Working
        uses: Long0x0/zju-ncov-hitcarder@0.0.3
        with:
          username: ${{ secrets[matrix.user.username] }}
          password: ${{ secrets[matrix.user.password] }}
          dingtalk_token: ${{ secrets[matrix.user.dingtalk_token] }}
          pushplus_token: ${{ secrets[matrix.user.pushplus_token] }}
          serverchan_key: ${{ secrets[matrix.user.serverchan_key] }}
